"""empty message

Revision ID: 773d39290f20
Revises: 
Create Date: 2021-12-11 21:37:03.485992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773d39290f20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
